### ISSUE TITLE
日記を見るページのUI

### ISSUE THREAD

**Issue by IkemotoNanako** [flutteruniv/omurice#10]
自分、フォロワー、タイムラインを切り替えられるようにする
アイコンと名前と日記とブックマークを付けるアイコンがひとまとまり
日記のフォーマットは5種類
検索はほかのissueで作る

<img src="https://user-images.githubusercontent.com/3205581/216607306-30f4f150-69a1-49c6-8861-b3d91b2059cf.png" width="320px">

**Comment by yukinkomob** [comment]
## 画面構成

* 検索バー
  - hint: キーワードで検索
* 上タブ
  - 自分
  - フォロワー
  - タイムライン
* リスト
  - 縦方向
* リストアイテム
  - アバター画像
  - 名前
    - （氏名がある場合に名前のみ表示？）
  - 日記の先頭部分
    - 最大5行
    - 5行未満の場合は高さを縮めて表示する？それとも5行分の高さで揃える？
  - ブックマークボタン
    - 押すとブックマークされる
    - ブックマーク時の画像はどうする？
      - 典型的な画像を利用する？

**Comment by yukinkomob** [comment]
## タブの表示条件

* それぞれレイアウト構成は同じと仮定して進める

* 自分タブ
  - 自分の書いた日記が表示される
* フォロワータブ
  - フォロワーの書いた日記が表示される
  - フォロワー＝自分をフォローしている人、だがそれで良い？
  - 自分がフォローした人の日記を見たいのでは？
* タイムラインタブ
  - 自分、フォロワーを含めた色々な人の日記が表示される？
  - 自分が行った何らかのアクションも表示する？（フォローしたとか、されたとか）
    - その場合のレイアウトは現在特に用意されていない
      - メッセージの部分だけ通知内容に置き換えたりすることは可能

**Comment by yukinkomob** [comment]
## 詳細仕様

* タブの実装
  - DefaultTabController, TabBar, TabBarViewを利用する
【Flutter】 タブで画面を切り替える方法 | 可茂IT塾
https://www.kamo-it.org/blog/25/

* タブの各画面
  - DiaryListScreenを作成
    - 引数としてmodeを設定
    - modeはenumで下記を用意する
      - 自分：MODE_MYSELF
      - フォロワー：MODE_FOLLOWER
      - タイムライン：MODE_TIMELINE
    - modeに沿った条件でデータを取得・表示することを想定する

* リスト
  - ListView.separated
    - itemBuilder: ダミーデータを渡す
    - separatedBuilder: 要素の間に置きたいウィジェット（Dividerを置く？）
    - itemCount: ダミーデータのサイズを渡す

[Flutter]ListView.separatedの使い方 | ちょげぶろぐ
https://www.choge-blog.com/programming/flutterlistview-separated-use/

  - Scrollbar
    - リストをラップする
    - thickness, isAlwaysShown, radiusなどが設定可能だが、デフォルトのままで良い

【Flutter】スクロール可能なリストにScrollbarを表示させる | 可茂IT塾
https://www.kamo-it.org/blog/flutter-scrollbar/

* リストアイテム
  - アバター画像：CircleAvatar
    - 画像がある場合：NetworkImageにURLを指定
    - 画像がない場合：background, child: Textを指定
  - 名前：Text
  - 日記の先頭部分：Text
  - ブックマークボタン：IconButton
    - ブックマークアイコン
      - 済み：Bookmark
      - 未：Bookmark Border

[Flutter]「IconButton（アイコンボタン）」の使い方 | ちょげぶろぐ
https://www.choge-blog.com/programming/flutter%E3%80%8Ciconbutton%EF%BC%88%E3%82%A2%E3%82%A4%E3%82%B3%E3%83%B3%E3%83%9C%E3%82%BF%E3%83%B3%EF%BC%89%E3%80%8D%E3%81%AE%E4%BD%BF%E3%81%84%E6%96%B9/

Material Symbols and Icons - Google Fonts
https://fonts.google.com/icons?selected=Material+Icons
