### ISSUE TITLE
日記のフォーマットを選ぶページUI

### ISSUE THREAD

**Issue by IkemotoNanako** [flutteruniv/omurice#3]
### Figma

![Image](https://user-images.githubusercontent.com/3205581/214736297-ec07d166-f4b5-467f-8a5b-1c9b6d1fa048.png)

https://www.figma.com/file/TRcAPZoQJtjn8u5LUSAgK8/%E3%83%A2%E3%83%83%E3%82%AF?node-id=0%3A1&t=Y1rBP4usQXNL14Gn-0

### 動画

https://user-images.githubusercontent.com/3205581/215131556-459da806-d903-45c1-acc7-c8b5e2e5d482.mov

**Comment by yukinkomob** [comment]
### 詳細仕様

* タイトルバー
  * 現在の日付を表示する
* コンテンツ
  * ５個の項目をグリッド形式で表示する
    * 五感日記
    * 過去の自分へ
    * 未来の自分になりきって
    * 使ったサービス
    * 自由に
* ナビゲーションバー
  * 左端に位置するボタンに紐づけられる
