### ISSUE TITLE
日記のsupabase設定

### ISSUE THREAD

**Issue by IkemotoNanako** [flutteruniv/omurice#34]
## Why

- バックエンドとデータのやり取りをしたい

## What

- 日記画面にて日記データの操作を実装する
  - 一時保存のデータはローカルのデータベースに保存するか不明であるため保留とする
    - そもそも保存機能は必要？
  - 日記の書き込み
- 日記の編集画面も用意する必要がある？
  - 編集画面のデザインもほぼ同じになる見込み

**Comment by yukinkomob** [comment]
担当を @IkemotoNanako さんに変更いたします
