### ISSUE TITLE
サービスのデータを充実させる

### ISSUE THREAD

**Issue by yukinkomob** [flutteruniv/omurice#45]
## Why

- サービスの内容として提供するデータが欲しい

## What

- 下記のスプレッドシートの内容を整理する
  - シート「サービス一覧」の情報をシート「生活」「お金」「仕事」「健康」のいずれかに移動する
  - シート「生活」「お金」「仕事」「健康」の情報で不足している内容を追記する
    - ただし、直近で必須でない情報は空白のままでも良い
    - 例：検索機能は現状追加しないため、検索に関係するデータはとりあえず不要と判断できる
- シート「生活」「お金」「仕事」「健康」にさらに情報を追記する
  - ネット検索などを介して、さらに情報を充実させる
- Supabaseのテーブルに情報を転記する
  - サンプルとして各3個ずつシートの情報をSupabaseのテーブルに値として登録する
  - 残りのデータはRyoさんが別タスクにて転記対応をしてくださるとのこと

**Comment by IkemotoNanako** [comment]
Supabaseのテーブルに情報を転記する
サンプルとして各3個ずつシートの情報をSupabaseのテーブルに値として登録する

こちら引き取ります！

**Comment by yukinkomob** [comment]
解決済み
