### ISSUE TITLE
自由に日記を書くページのUI

### ISSUE THREAD

**Issue by IkemotoNanako** [flutteruniv/omurice#8]
### 想定要件

* 本画面は全画面のモーダルダイアログとして開く
* 本画面ではフォーマットの適用は行わない
* 下記のボタンを有する
  - Xボタン
  - 保存ボタン
  - 投稿ボタン
* Xボタン押下時に日記の内容が保存されていない場合は確認ダイアログを出し、一時保存をするかどうかを選択する
* 投稿ボタンを押下するとタイムラインに投稿した日記が表示される
* 保存ボタンを押下すると書いた内容を一時的に保存することができる

### Figma

<img src="https://user-images.githubusercontent.com/3205581/215136467-c246f30d-0a6f-40a8-904e-fa9ddc89025b.png" width="320px">

**Comment by yukinkomob** [comment]
マージ待ちの項目が２個あるので、そちらがマージされたらこちらのPRを作成する。
